FROM alpine
RUN apk --no-cache --update-cache add gcc gfortran python python-dev py-pip build-base wget freetype-dev
RUN ln -s /usr/include/locale.h /usr/include/xlocale.h
RUN pip install numpy
RUN pip install flask
COPY . .
CMD ["python", "hello.py"]